# Generated by Django 6.0.6 on 2026-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(choices=[('conductor', 'Conductor'), ('vehiculo', 'Vehículo'), ('trailer', 'Trailer')], max_length=20)),
                ('id_objeto', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=100)),
                ('fecha_termina', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
    ]
