# Generated by Django 6.0.6 on 2026-06-30 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('viajes', '0004_rename_fecha_llegada_viaje_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='fecha_termina',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='id_objeto',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo_objeto',
        ),
        migrations.AddField(
            model_name='documento',
            name='numero',
            field=models.CharField(default='Sin número', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('remesa', 'Remesa'), ('manifiesto', 'Manifiesto'), ('factura', 'Factura'), ('soporte', 'Soporte'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='viaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje'),
            preserve_default=False,
        ),
    ]
