# Generated by Django 6.0.6 on 2026-07-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0003_rename_numero_conductor_telefono_and_more'),
        ('documentos', '0002_rename_fecha_termina_documento_fecha_and_more'),
        ('vehiculos', '0001_initial'),
        ('viajes', '0004_rename_fecha_llegada_viaje_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='fecha',
            new_name='fecha_expedicion',
        ),
        migrations.AddField(
            model_name='documento',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conductores.conductor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('licencia', 'Licencia de conducción'), ('soat', 'SOAT'), ('tecnomecanica', 'Tecnomecánica'), ('tarjeta', 'Tarjeta de propiedad'), ('poliza', 'Póliza'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documento',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje'),
        ),
    ]
