# Generated by Django 6.0.7 on 2026-08-04 14:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_rename_fecha_documento_fecha_expedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
    ]
