# Generated by Django 6.0.6 on 2026-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=80)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
            ],
        ),
    ]
