# Generated by Django 6.0.6 on 2026-06-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0001_initial'),
        ('trailers', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('flete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conductores.conductor')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trailers.trailer')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo')),
            ],
        ),
    ]
