# Generated by Django 6.0.6 on 2026-06-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_alter_conductor_estado_alter_conductor_numero'),
        ('trailers', '0002_alter_trailer_kilometraje'),
        ('vehiculos', '0001_initial'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='fecha_fin',
            new_name='fecha_llegada',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='fecha_inicio',
            new_name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='anticipo',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='flete',
        ),
        migrations.AddField(
            model_name='viaje',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='conductores.conductor'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='trailers.trailer'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='vehiculos.vehiculo'),
        ),
    ]
