# Generated by Django 6.0.6 on 2026-06-30 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_alter_conductor_estado_alter_conductor_numero'),
        ('trailers', '0002_alter_trailer_kilometraje'),
        ('vehiculos', '0001_initial'),
        ('viajes', '0002_rename_fecha_fin_viaje_fecha_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conductores.conductor'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trailers.trailer'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo'),
        ),
    ]
