# Generated by Django 6.0.6 on 2026-06-30 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("viajes", "0003_alter_viaje_conductor_alter_viaje_estado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="viaje",
            old_name="fecha_llegada",
            new_name="fecha_fin",
        ),

        migrations.RenameField(
            model_name="viaje",
            old_name="fecha_salida",
            new_name="fecha_inicio",
        ),

        migrations.RemoveField(
            model_name="viaje",
            name="observaciones",
        ),

        migrations.AddField(
            model_name="viaje",
            name="anticipo",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0,
            ),
        ),

        migrations.AddField(
            model_name="viaje",
            name="cliente",
            field=models.CharField(
                max_length=150,
                default="Sin cliente",
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="viaje",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),

        migrations.AddField(
            model_name="viaje",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="viaje",
            name="flete",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0,
            ),
        ),
    ]