# Generated by Django 6.0.6 on 2026-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(choices=[('vehiculo', 'Vehículo'), ('trailer', 'Trailer')], max_length=20)),
                ('id_objeto', models.IntegerField()),
                ('nombre_mantenimiento', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('km_actual', models.IntegerField()),
                ('km_duracion', models.IntegerField(help_text='Kilómetros para próximo mantenimiento')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='mantenimientos/')),
            ],
        ),
    ]
