# Generated by Django 6.0.6 on 2026-07-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
        ('trailers', '0002_alter_trailer_kilometraje'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='id_objeto',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo_objeto',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trailers.trailer'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='km_duracion',
            field=models.IntegerField(help_text='Kilómetros para el próximo mantenimiento'),
        ),
    ]
