# Generated by Django 6.0.6 on 2026-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('kilometraje_actual', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
            ],
        ),
    ]
