# Generated by Django 6.0.7 on 2026-07-10 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('peajes', 'Peajes'), ('viaticos', 'Viáticos'), ('mantenimiento', 'Mantenimiento'), ('pago_viaje', 'Pago de Viaje'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
