# Generated by Django 6.0.6 on 2026-06-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_personalizado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recibo', models.FileField(blank=True, null=True, upload_to='recibos/')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viajes.viaje')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.tipogasto')),
            ],
        ),
    ]
