# Generated by Django 6.0.6 on 2026-06-30 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        ('viajes', '0004_rename_fecha_llegada_viaje_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('combustible', 'Combustible'), ('peaje', 'Peaje'), ('alimentacion', 'Alimentación'), ('hospedaje', 'Hospedaje'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='recibo',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='tipo_personalizado',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje'),
        ),
        migrations.DeleteModel(
            name='TipoGasto',
        ),
    ]
