# Generated by Django 6.0.6 on 2026-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
