# Generated by Django 6.0.6 on 2026-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_alter_conductor_estado_alter_conductor_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='numero',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='cedula',
        ),
        migrations.AddField(
            model_name='conductor',
            name='licencia',
            field=models.CharField(default='Sin licencia', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
