# Generated by Django 6.0.7 on 2026-07-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0004_conductor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='licencia',
        ),
    ]
